version: '3.3'
services:
  db:
    image: biarms/mysql:5.5.60
    restart: always
    environment:
       MYSQL_DATABASE: wordpress_db
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    #command: --init-file ./init.sql    
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data-wordpress/sql:/var/lib/mysql

  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./data-wordpress/html:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress_db
